name: leancode_cubit_utils_cqrs
description: An extension of leancode_cubit_utils that provides cqrs support.
version: 0.5.0
repository: https://github.com/leancodepl/leancode_cubit_utils

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cqrs: ^10.0.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  leancode_cubit_utils:
    # TODO: Replace with pub.dev version when `leancode_cubit_utils` version `0.5.0` is released.
    git:
      url: git@github.com:leancodepl/leancode_cubit_utils.git
      ref: fix/query-cubit-handling-on-empty-state
      path: packages/leancode_cubit_utils
  leancode_hooks: ^0.1.1

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  leancode_lint: ^15.0.0
  mocktail: ^1.0.4
