name: leancode_cubit_utils test

on:
  push:
    branches: [main]
    tags-ignore: ['leancode_cubit_utils-v*']
    paths:
      - 'packages/leancode_cubit_utils/**'
  pull_request:
    branches: [main]
    paths:
      - 'packages/leancode_cubit_utils/**'

jobs:
  test:
    name: Flutter ${{ matrix.version }}

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: '3.35.x'

    defaults:
      run:
        working-directory: packages/leancode_cubit_utils

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          cache: true

      - name: Download pub dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --set-exit-if-changed --output none .

      - name: Run analyzer
        run: flutter analyze --fatal-warnings --fatal-infos

      - name: Run tests
        run: flutter test

      - name: Dry run pub publish
        run: dart pub publish --dry-run || true
