name: leancode_cubit_utils
description: A collection of cubits and widgets that facilitate the creation of repetitive pages, eliminating boilerplate.
version: 0.1.0
repository: https://github.com/leancodepl/leancode_cubit_utils

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  async: ^2.0.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  leancode_hooks: ^0.0.6
  logging: ^1.0.0
  provider: ^6.0.0

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  http: ^1.2.1
  leancode_lint: ^9.0.0
  mocktail: ^1.0.0
