name: leancode_cubit_utils
description: A collection of cubits and widgets that facilitate the creation of repetitive pages, eliminating boilerplate.
version: 0.4.1
repository: https://github.com/leancodepl/leancode_cubit_utils

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  async: ^2.11.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  leancode_hooks: ^0.1.1
  logging: ^1.3.0
  provider: ^6.1.5

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  http: ^1.3.0
  leancode_lint: ^15.0.0
  mocktail: ^1.0.4
